"""persist agent workspace control plane and vault

Revision ID: 0016_agent_workspace
Revises: 0015_tutor_conversations
Create Date: 2026-08-28 23:30:15.473626
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0016_agent_workspace"
down_revision: str | Sequence[str] | None = "0015_tutor_conversations"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _sha256_check(column_name: str) -> str:
    stripped = column_name
    for character in "0123456789abcdef":
        stripped = f"replace({stripped}, '{character}', '')"
    return f"length({column_name}) = 64 AND {stripped} = ''"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_provider_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=False),
        sa.Column(
            "available_tools",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "endpoint_metadata",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("secret_reference", sa.String(length=1024), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("health_status", sa.String(length=100), server_default="unknown", nullable=False),
        sa.Column("last_health_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("config_version > 0", name="ck_agent_provider_config_version_positive"),
        sa.CheckConstraint("context_window > 0", name="ck_agent_provider_context_positive"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_agent_provider_setting_user", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_agent_provider_setting_user_provider"),
    )
    op.create_index(
        op.f("ix_agent_provider_settings_health_status"),
        "agent_provider_settings",
        ["health_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_provider_settings_provider"),
        "agent_provider_settings",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_provider_settings_user_id"),
        "agent_provider_settings",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=100), server_default="claude", nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column(
            "permission_mode",
            sa.String(length=100),
            server_default="bypassPermissions",
            nullable=False,
        ),
        sa.Column("native_session_id", sa.String(length=512), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "running",
                "waiting_input",
                "stopped",
                "failed",
                "archived",
                name="agent_session_state",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="running",
            nullable=False,
        ),
        sa.Column("parent_session_id", sa.Uuid(), nullable=True),
        sa.Column("forked_from_turn_id", sa.Uuid(), nullable=True),
        sa.Column("rewind_checkpoint_id", sa.String(length=512), nullable=True),
        sa.Column("last_event_sequence", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "recovery",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "last_event_sequence >= 0", name="ck_agent_session_last_sequence_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id", "space_id"],
            ["knowledge_bases.id", "knowledge_bases.space_id"],
            name="fk_agent_session_knowledge_base_space",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_session_id"],
            ["agent_sessions.id"],
            name="fk_agent_session_parent",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"], ["spaces.id"], name="fk_agent_session_space", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_agent_session_user", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id", "user_id", "space_id", "knowledge_base_id", name="uq_agent_session_scope"
        ),
        sa.UniqueConstraint("id", "user_id", name="uq_agent_session_owner"),
    )
    op.create_index(
        op.f("ix_agent_sessions_forked_from_turn_id"),
        "agent_sessions",
        ["forked_from_turn_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_sessions_knowledge_base_id"),
        "agent_sessions",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_sessions_native_session_id"),
        "agent_sessions",
        ["native_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_sessions_parent_session_id"),
        "agent_sessions",
        ["parent_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_sessions_space_id"), "agent_sessions", ["space_id"], unique=False
    )
    op.create_index(op.f("ix_agent_sessions_state"), "agent_sessions", ["state"], unique=False)
    op.create_index(op.f("ix_agent_sessions_user_id"), "agent_sessions", ["user_id"], unique=False)
    op.create_table(
        "vault_sync_cursors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column("watcher_cursor", sa.String(length=2048), nullable=True),
        sa.Column("database_cursor", sa.String(length=2048), nullable=True),
        sa.Column("index_cursor", sa.String(length=2048), nullable=True),
        sa.Column("pending_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("requires_full_scan", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("pending_count >= 0", name="ck_vault_sync_cursor_pending_nonnegative"),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id", "space_id"],
            ["knowledge_bases.id", "knowledge_bases.space_id"],
            name="fk_vault_sync_cursor_knowledge_base_space",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"], ["spaces.id"], name="fk_vault_sync_cursor_space", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("knowledge_base_id", name="uq_vault_sync_cursor_knowledge_base"),
    )
    op.create_index(
        op.f("ix_vault_sync_cursors_knowledge_base_id"),
        "vault_sync_cursors",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vault_sync_cursors_requires_full_scan"),
        "vault_sync_cursors",
        ["requires_full_scan"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vault_sync_cursors_space_id"), "vault_sync_cursors", ["space_id"], unique=False
    )
    op.create_table(
        "agent_turns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_message", sa.Text(), server_default="", nullable=False),
        sa.Column("response_summary", sa.Text(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "running",
                "waiting_input",
                "completed",
                "stopped",
                "failed",
                name="agent_turn_state",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="running",
            nullable=False,
        ),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column(
            "context_statistics",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("source_kind", sa.String(length=50), nullable=True),
        sa.Column("source_turn_id", sa.Uuid(), nullable=True),
        sa.Column("native_turn_id", sa.String(length=512), nullable=True),
        sa.Column("native_session_id", sa.String(length=512), nullable=True),
        sa.Column("rewind_checkpoint_id", sa.String(length=512), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("cache_tokens >= 0", name="ck_agent_turn_cache_tokens_nonnegative"),
        sa.CheckConstraint("input_tokens >= 0", name="ck_agent_turn_input_tokens_nonnegative"),
        sa.CheckConstraint("output_tokens >= 0", name="ck_agent_turn_output_tokens_nonnegative"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["agent_sessions.id"], name="fk_agent_turn_session", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_turn_id"], ["agent_turns.id"], name="fk_agent_turn_source", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_turns_native_session_id"), "agent_turns", ["native_session_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_turns_native_turn_id"), "agent_turns", ["native_turn_id"], unique=False
    )
    op.create_index(op.f("ix_agent_turns_session_id"), "agent_turns", ["session_id"], unique=False)
    op.create_index(
        op.f("ix_agent_turns_source_turn_id"), "agent_turns", ["source_turn_id"], unique=False
    )
    op.create_index(op.f("ix_agent_turns_state"), "agent_turns", ["state"], unique=False)
    op.create_table(
        "agent_workspace_grants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column("can_read", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("can_write", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("can_delete", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "tool_categories",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("vault_root", sa.String(length=2048), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("nonce", sa.String(length=255), nullable=False),
        sa.Column("signature", sa.String(length=512), nullable=False),
        sa.Column("capability_version", sa.String(length=50), server_default="1.0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("expires_at > issued_at", name="ck_agent_workspace_grant_expiry"),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id", "space_id"],
            ["knowledge_bases.id", "knowledge_bases.space_id"],
            name="fk_agent_workspace_grant_knowledge_base_space",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "user_id"],
            ["agent_sessions.id", "agent_sessions.user_id"],
            name="fk_agent_workspace_grant_session_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nonce", name="uq_agent_workspace_grant_nonce"),
        sa.UniqueConstraint(
            "session_id", "knowledge_base_id", name="uq_agent_workspace_grant_session_kb"
        ),
    )
    op.create_index(
        op.f("ix_agent_workspace_grants_expires_at"),
        "agent_workspace_grants",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_workspace_grants_knowledge_base_id"),
        "agent_workspace_grants",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_workspace_grants_nonce"), "agent_workspace_grants", ["nonce"], unique=False
    )
    op.create_index(
        op.f("ix_agent_workspace_grants_session_id"),
        "agent_workspace_grants",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_workspace_grants_space_id"),
        "agent_workspace_grants",
        ["space_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_workspace_grants_user_id"),
        "agent_workspace_grants",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "agent_audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("turn_id", sa.Uuid(), nullable=True),
        sa.Column("change_set_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=True),
        sa.Column("tool_call_id", sa.String(length=512), nullable=True),
        sa.Column("command", sa.Text(), nullable=True),
        sa.Column("file_operation", sa.String(length=100), nullable=True),
        sa.Column("source_path", sa.String(length=2048), nullable=True),
        sa.Column("target_path", sa.String(length=2048), nullable=True),
        sa.Column("url", sa.String(length=4096), nullable=True),
        sa.Column("mcp_server", sa.String(length=255), nullable=True),
        sa.Column("mcp_tool", sa.String(length=255), nullable=True),
        sa.Column("skill_name", sa.String(length=255), nullable=True),
        sa.Column("subagent_id", sa.String(length=512), nullable=True),
        sa.Column("before_hash", sa.String(length=64), nullable=True),
        sa.Column("after_hash", sa.String(length=64), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=100), server_default="completed", nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("sidecar_reference", sa.String(length=2048), nullable=True),
        sa.Column(
            "arguments_summary",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "after_hash IS NULL OR " + _sha256_check("after_hash"),
            name="ck_agent_audit_after_hash",
        ),
        sa.CheckConstraint(
            "before_hash IS NULL OR " + _sha256_check("before_hash"),
            name="ck_agent_audit_before_hash",
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0", name="ck_agent_audit_duration_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_sessions.id"],
            name="fk_agent_audit_session",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["agent_turns.id"], name="fk_agent_audit_turn", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_agent_audit_user", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_audit_events_change_set_id"),
        "agent_audit_events",
        ["change_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_audit_events_created_at"), "agent_audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_agent_audit_events_event_type"), "agent_audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_agent_audit_events_session_id"), "agent_audit_events", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_audit_events_tool_call_id"),
        "agent_audit_events",
        ["tool_call_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_audit_events_tool_name"), "agent_audit_events", ["tool_name"], unique=False
    )
    op.create_index(
        op.f("ix_agent_audit_events_turn_id"), "agent_audit_events", ["turn_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_audit_events_user_id"), "agent_audit_events", ["user_id"], unique=False
    )
    op.create_table(
        "agent_session_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("turn_id", sa.Uuid(), nullable=True),
        sa.Column("tool_call_id", sa.String(length=512), nullable=True),
        sa.Column("subagent_id", sa.String(length=512), nullable=True),
        sa.Column("completed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sidecar_reference", sa.String(length=2048), nullable=True),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(event_type)) > 0", name="ck_agent_event_type_nonempty"),
        sa.CheckConstraint(
            "length(trim(idempotency_key)) > 0", name="ck_agent_event_idempotency_nonempty"
        ),
        sa.CheckConstraint("sequence > 0", name="ck_agent_event_sequence_positive"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["agent_sessions.id"], name="fk_agent_event_session", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["agent_turns.id"], name="fk_agent_event_turn", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", name="uq_agent_event_id"),
        sa.UniqueConstraint("idempotency_key", name="uq_agent_event_idempotency_key"),
        sa.UniqueConstraint("session_id", "sequence", name="uq_agent_event_session_sequence"),
    )
    op.create_index(
        op.f("ix_agent_session_events_completed"),
        "agent_session_events",
        ["completed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_session_events_created_at"),
        "agent_session_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_session_events_event_id"), "agent_session_events", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_session_events_event_type"),
        "agent_session_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_session_events_idempotency_key"),
        "agent_session_events",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_session_events_session_id"),
        "agent_session_events",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_session_events_subagent_id"),
        "agent_session_events",
        ["subagent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_session_events_tool_call_id"),
        "agent_session_events",
        ["tool_call_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_session_events_turn_id"), "agent_session_events", ["turn_id"], unique=False
    )
    op.create_table(
        "agent_usage_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("compaction_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tool_call_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("web_request_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("file_read_bytes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("command_duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sidecar_bytes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("session_duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("provider_error", sa.String(length=255), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cache_read_tokens >= 0", name="ck_agent_usage_cache_read_tokens_nonnegative"
        ),
        sa.CheckConstraint(
            "cache_write_tokens >= 0", name="ck_agent_usage_cache_write_tokens_nonnegative"
        ),
        sa.CheckConstraint(
            "command_duration_ms >= 0", name="ck_agent_usage_command_duration_ms_nonnegative"
        ),
        sa.CheckConstraint(
            "compaction_count >= 0", name="ck_agent_usage_compaction_count_nonnegative"
        ),
        sa.CheckConstraint(
            "file_read_bytes >= 0", name="ck_agent_usage_file_read_bytes_nonnegative"
        ),
        sa.CheckConstraint("input_tokens >= 0", name="ck_agent_usage_input_tokens_nonnegative"),
        sa.CheckConstraint("output_tokens >= 0", name="ck_agent_usage_output_tokens_nonnegative"),
        sa.CheckConstraint(
            "session_duration_ms >= 0", name="ck_agent_usage_session_duration_ms_nonnegative"
        ),
        sa.CheckConstraint("sidecar_bytes >= 0", name="ck_agent_usage_sidecar_bytes_nonnegative"),
        sa.CheckConstraint(
            "tool_call_count >= 0", name="ck_agent_usage_tool_call_count_nonnegative"
        ),
        sa.CheckConstraint(
            "web_request_count >= 0", name="ck_agent_usage_web_request_count_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["agent_sessions.id"], name="fk_agent_usage_session", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["agent_turns.id"], name="fk_agent_usage_turn", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_usage_records_provider_error"),
        "agent_usage_records",
        ["provider_error"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_usage_records_recorded_at"),
        "agent_usage_records",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_usage_records_session_id"),
        "agent_usage_records",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_usage_records_turn_id"), "agent_usage_records", ["turn_id"], unique=False
    )
    op.create_table(
        "vault_change_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "agent",
                "shell",
                "git",
                "external_editor",
                "api",
                "initial_migration",
                "conflict_backup",
                name="vault_change_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "applying",
                "committed",
                "conflicted",
                "indexing",
                "indexed",
                "failed",
                name="vault_change_set_state",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("turn_id", sa.Uuid(), nullable=True),
        sa.Column("tool_call_id", sa.String(length=512), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("before_snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("after_snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("conflicted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "after_snapshot_hash IS NULL OR " + _sha256_check("after_snapshot_hash"),
            name="ck_vault_change_set_after_snapshot_hash",
        ),
        sa.CheckConstraint(
            "before_snapshot_hash IS NULL OR " + _sha256_check("before_snapshot_hash"),
            name="ck_vault_change_set_before_snapshot_hash",
        ),
        sa.CheckConstraint("retry_count >= 0", name="ck_vault_change_set_retry_nonnegative"),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id", "space_id"],
            ["knowledge_bases.id", "knowledge_bases.space_id"],
            name="fk_vault_change_set_knowledge_base_space",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_sessions.id"],
            name="fk_vault_change_set_session",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"], ["spaces.id"], name="fk_vault_change_set_space", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["agent_turns.id"], name="fk_vault_change_set_turn", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id", "knowledge_base_id", "space_id", name="uq_vault_change_set_scope"
        ),
    )
    op.create_index(
        op.f("ix_vault_change_sets_created_at"), "vault_change_sets", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_vault_change_sets_failure_code"),
        "vault_change_sets",
        ["failure_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vault_change_sets_knowledge_base_id"),
        "vault_change_sets",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vault_change_sets_session_id"), "vault_change_sets", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_vault_change_sets_source"), "vault_change_sets", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_vault_change_sets_space_id"), "vault_change_sets", ["space_id"], unique=False
    )
    op.create_index(
        op.f("ix_vault_change_sets_state"), "vault_change_sets", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_vault_change_sets_tool_call_id"),
        "vault_change_sets",
        ["tool_call_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vault_change_sets_turn_id"), "vault_change_sets", ["turn_id"], unique=False
    )
    op.create_table(
        "vault_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column("relative_path", sa.String(length=2048), nullable=False),
        sa.Column(
            "file_kind",
            sa.Enum(
                "markdown",
                "attachment",
                "sidecar",
                "other",
                name="vault_file_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("filesystem_mtime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_identity", sa.String(length=1024), nullable=True),
        sa.Column(
            "sync_state",
            sa.Enum(
                "pending",
                "synced",
                "conflict",
                "failed",
                "tombstoned",
                name="vault_sync_state",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("last_change_set_id", sa.Uuid(), nullable=True),
        sa.Column("is_tombstoned", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("tombstoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_index_version_id", sa.Uuid(), nullable=True),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relative_path NOT LIKE '%\\%' ESCAPE '!'",
            name="ck_vault_file_path_posix",
        ),
        sa.CheckConstraint(
            _sha256_check("content_hash"),
            name="ck_vault_file_content_hash",
        ),
        sa.CheckConstraint(
            "relative_path <> '.' AND relative_path NOT LIKE './%' "
            "AND relative_path NOT LIKE '%/./%' AND relative_path NOT LIKE '%/.'",
            name="ck_vault_file_path_normalized",
        ),
        sa.CheckConstraint(
            "relative_path <> '..' AND relative_path NOT LIKE '../%' "
            "AND relative_path NOT LIKE '%/../%' AND relative_path NOT LIKE '%/..'",
            name="ck_vault_file_path_no_parent",
        ),
        sa.CheckConstraint(
            "substr(relative_path, 1, 1) <> '/'", name="ck_vault_file_path_relative"
        ),
        sa.CheckConstraint(
            "(is_tombstoned = false AND tombstoned_at IS NULL) OR is_tombstoned = true",
            name="ck_vault_file_tombstone_timestamp",
        ),
        sa.CheckConstraint("length(relative_path) > 0", name="ck_vault_file_path_nonempty"),
        sa.CheckConstraint(
            "relative_path = trim(relative_path)", name="ck_vault_file_path_trimmed"
        ),
        sa.CheckConstraint("revision >= 0", name="ck_vault_file_revision_nonnegative"),
        sa.CheckConstraint("size_bytes >= 0", name="ck_vault_file_size_nonnegative"),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id", "space_id"],
            ["knowledge_bases.id", "knowledge_bases.space_id"],
            name="fk_vault_file_knowledge_base_space",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["last_change_set_id"],
            ["vault_change_sets.id"],
            name="fk_vault_file_last_change_set",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["last_index_version_id"],
            ["index_versions.id"],
            name="fk_vault_file_last_index",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"], ["spaces.id"], name="fk_vault_file_space", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "knowledge_base_id", "space_id", name="uq_vault_file_scope"),
        sa.UniqueConstraint(
            "knowledge_base_id", "relative_path", name="uq_vault_file_path_in_knowledge_base"
        ),
    )
    op.create_index(
        op.f("ix_vault_files_content_hash"), "vault_files", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_vault_files_file_identity"), "vault_files", ["file_identity"], unique=False
    )
    op.create_index(op.f("ix_vault_files_file_kind"), "vault_files", ["file_kind"], unique=False)
    op.create_index(
        op.f("ix_vault_files_is_tombstoned"), "vault_files", ["is_tombstoned"], unique=False
    )
    op.create_index(
        op.f("ix_vault_files_knowledge_base_id"), "vault_files", ["knowledge_base_id"], unique=False
    )
    op.create_index(
        op.f("ix_vault_files_last_change_set_id"),
        "vault_files",
        ["last_change_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vault_files_last_index_version_id"),
        "vault_files",
        ["last_index_version_id"],
        unique=False,
    )
    op.create_index(op.f("ix_vault_files_space_id"), "vault_files", ["space_id"], unique=False)
    op.create_index(op.f("ix_vault_files_sync_state"), "vault_files", ["sync_state"], unique=False)
    op.create_table(
        "semantic_index_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column("vault_file_id", sa.Uuid(), nullable=False),
        sa.Column("change_set_id", sa.Uuid(), nullable=True),
        sa.Column("index_version_id", sa.Uuid(), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "validating",
                "validated",
                "stale",
                "applied",
                "failed",
                name="semantic_index_plan_state",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "validation_errors",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("raw_sidecar_reference", sa.String(length=2048), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            _sha256_check("input_hash"),
            name="ck_semantic_index_plan_input_hash",
        ),
        sa.CheckConstraint(
            _sha256_check("prompt_hash"),
            name="ck_semantic_index_plan_prompt_hash",
        ),
        sa.CheckConstraint("retry_count >= 0", name="ck_semantic_index_plan_retry_nonnegative"),
        sa.ForeignKeyConstraint(
            ["change_set_id"],
            ["vault_change_sets.id"],
            name="fk_semantic_index_plan_change_set",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["index_version_id"],
            ["index_versions.id"],
            name="fk_semantic_index_plan_index",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id", "space_id"],
            ["knowledge_bases.id", "knowledge_bases.space_id"],
            name="fk_semantic_index_plan_knowledge_base_space",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vault_file_id", "knowledge_base_id", "space_id"],
            ["vault_files.id", "vault_files.knowledge_base_id", "vault_files.space_id"],
            name="fk_semantic_index_plan_file_scope",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "vault_file_id",
            "input_hash",
            "schema_version",
            "prompt_hash",
            name="uq_semantic_index_plan_input_contract",
        ),
    )
    op.create_index(
        op.f("ix_semantic_index_plans_change_set_id"),
        "semantic_index_plans",
        ["change_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_index_plans_failure_code"),
        "semantic_index_plans",
        ["failure_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_index_plans_index_version_id"),
        "semantic_index_plans",
        ["index_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_index_plans_input_hash"),
        "semantic_index_plans",
        ["input_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_index_plans_knowledge_base_id"),
        "semantic_index_plans",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_index_plans_space_id"), "semantic_index_plans", ["space_id"], unique=False
    )
    op.create_index(
        op.f("ix_semantic_index_plans_state"), "semantic_index_plans", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_semantic_index_plans_vault_file_id"),
        "semantic_index_plans",
        ["vault_file_id"],
        unique=False,
    )
    op.create_table(
        "vault_change_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("change_set_id", sa.Uuid(), nullable=False),
        sa.Column("vault_file_id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "operation",
            sa.Enum(
                "create",
                "update",
                "move",
                "rename",
                "delete",
                name="vault_change_operation",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("before_path", sa.String(length=2048), nullable=True),
        sa.Column("after_path", sa.String(length=2048), nullable=True),
        sa.Column("before_hash", sa.String(length=64), nullable=True),
        sa.Column("after_hash", sa.String(length=64), nullable=True),
        sa.Column("size_delta_bytes", sa.Integer(), nullable=True),
        sa.Column("audit_event_id", sa.Uuid(), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "after_hash IS NULL OR " + _sha256_check("after_hash"),
            name="ck_vault_change_entry_after_hash",
        ),
        sa.CheckConstraint(
            "before_hash IS NULL OR " + _sha256_check("before_hash"),
            name="ck_vault_change_entry_before_hash",
        ),
        sa.CheckConstraint("ordinal >= 0", name="ck_vault_change_entry_ordinal_nonnegative"),
        sa.CheckConstraint(
            "size_delta_bytes IS NULL OR size_delta_bytes >= -9223372036854775807",
            name="ck_vault_change_entry_size_delta",
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["agent_audit_events.id"],
            name="fk_vault_change_entry_audit",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["change_set_id", "knowledge_base_id", "space_id"],
            [
                "vault_change_sets.id",
                "vault_change_sets.knowledge_base_id",
                "vault_change_sets.space_id",
            ],
            name="fk_vault_change_entry_change_set_scope",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vault_file_id", "knowledge_base_id", "space_id"],
            ["vault_files.id", "vault_files.knowledge_base_id", "vault_files.space_id"],
            name="fk_vault_change_entry_file_scope",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("change_set_id", "ordinal", name="uq_vault_change_entry_ordinal"),
    )
    op.create_index(
        op.f("ix_vault_change_entries_audit_event_id"),
        "vault_change_entries",
        ["audit_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vault_change_entries_change_set_id"),
        "vault_change_entries",
        ["change_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vault_change_entries_knowledge_base_id"),
        "vault_change_entries",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vault_change_entries_operation"),
        "vault_change_entries",
        ["operation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vault_change_entries_space_id"), "vault_change_entries", ["space_id"], unique=False
    )
    op.create_index(
        op.f("ix_vault_change_entries_vault_file_id"),
        "vault_change_entries",
        ["vault_file_id"],
        unique=False,
    )
    with op.batch_alter_table("markdown_notes") as batch:
        batch.add_column(sa.Column("vault_file_id", sa.Uuid(), nullable=True))
        batch.add_column(sa.Column("vault_relative_path", sa.String(length=2048), nullable=True))
        batch.add_column(sa.Column("content_hash", sa.String(length=64), nullable=True))
        batch.add_column(
            sa.Column("sync_state", sa.String(length=50), server_default="pending", nullable=False)
        )
        batch.add_column(sa.Column("last_change_set_id", sa.Uuid(), nullable=True))
        batch.add_column(
            sa.Column("is_tombstoned", sa.Boolean(), server_default="false", nullable=False)
        )
        batch.add_column(sa.Column("tombstoned_at", sa.DateTime(timezone=True), nullable=True))
        batch.create_check_constraint(
            "ck_markdown_note_content_hash",
            "content_hash IS NULL OR " + _sha256_check("content_hash"),
        )
        batch.create_foreign_key(
            "fk_markdown_note_vault_file_kb_space",
            "vault_files",
            ["vault_file_id", "knowledge_base_id", "space_id"],
            ["id", "knowledge_base_id", "space_id"],
        )
        batch.create_foreign_key(
            "fk_markdown_note_last_change_set",
            "vault_change_sets",
            ["last_change_set_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch.create_index("ix_markdown_notes_vault_file_id", ["vault_file_id"], unique=True)
        batch.create_index("ix_markdown_notes_content_hash", ["content_hash"], unique=False)
        batch.create_index("ix_markdown_notes_sync_state", ["sync_state"], unique=False)
        batch.create_index(
            "ix_markdown_notes_last_change_set_id", ["last_change_set_id"], unique=False
        )
        batch.create_index("ix_markdown_notes_is_tombstoned", ["is_tombstoned"], unique=False)

    with op.batch_alter_table("markdown_revisions") as batch:
        batch.add_column(sa.Column("change_set_id", sa.Uuid(), nullable=True))
        batch.add_column(sa.Column("agent_session_id", sa.Uuid(), nullable=True))
        batch.add_column(sa.Column("agent_turn_id", sa.Uuid(), nullable=True))
        batch.add_column(sa.Column("tool_call_id", sa.String(length=512), nullable=True))
        batch.add_column(sa.Column("change_source", sa.String(length=100), nullable=True))
        batch.add_column(sa.Column("before_hash", sa.String(length=64), nullable=True))
        batch.add_column(sa.Column("after_hash", sa.String(length=64), nullable=True))
        batch.create_check_constraint(
            "ck_markdown_revision_before_hash",
            "before_hash IS NULL OR " + _sha256_check("before_hash"),
        )
        batch.create_check_constraint(
            "ck_markdown_revision_after_hash",
            "after_hash IS NULL OR " + _sha256_check("after_hash"),
        )
        batch.create_foreign_key(
            "fk_markdown_revision_change_set",
            "vault_change_sets",
            ["change_set_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch.create_foreign_key(
            "fk_markdown_revision_agent_session",
            "agent_sessions",
            ["agent_session_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch.create_foreign_key(
            "fk_markdown_revision_agent_turn",
            "agent_turns",
            ["agent_turn_id"],
            ["id"],
            ondelete="SET NULL",
        )
        for column in (
            "change_set_id",
            "agent_session_id",
            "agent_turn_id",
            "tool_call_id",
            "change_source",
            "before_hash",
            "after_hash",
        ):
            batch.create_index(f"ix_markdown_revisions_{column}", [column], unique=False)

    with op.batch_alter_table("index_versions") as batch:
        batch.add_column(sa.Column("planner_provider", sa.String(length=100), nullable=True))
        batch.add_column(sa.Column("planner_model", sa.String(length=255), nullable=True))
        batch.add_column(sa.Column("planner_schema_version", sa.String(length=50), nullable=True))
        batch.add_column(sa.Column("planner_prompt_hash", sa.String(length=64), nullable=True))
        batch.add_column(sa.Column("source_change_set_id", sa.Uuid(), nullable=True))
        batch.add_column(sa.Column("source_snapshot_hash", sa.String(length=64), nullable=True))
        batch.add_column(
            sa.Column(
                "activation_status", sa.String(length=50), server_default="pending", nullable=False
            )
        )
        batch.create_check_constraint(
            "ck_index_planner_prompt_hash",
            "planner_prompt_hash IS NULL OR " + _sha256_check("planner_prompt_hash"),
        )
        batch.create_check_constraint(
            "ck_index_source_snapshot_hash",
            "source_snapshot_hash IS NULL OR " + _sha256_check("source_snapshot_hash"),
        )
        batch.create_foreign_key(
            "fk_index_version_source_change_set",
            "vault_change_sets",
            ["source_change_set_id"],
            ["id"],
            ondelete="SET NULL",
        )
        for column in (
            "planner_prompt_hash",
            "source_change_set_id",
            "source_snapshot_hash",
            "activation_status",
        ):
            batch.create_index(f"ix_index_versions_{column}", [column], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table("index_versions") as batch:
        batch.drop_index("ix_index_versions_activation_status")
        batch.drop_index("ix_index_versions_source_snapshot_hash")
        batch.drop_index("ix_index_versions_source_change_set_id")
        batch.drop_index("ix_index_versions_planner_prompt_hash")
        batch.drop_constraint("fk_index_version_source_change_set", type_="foreignkey")
        batch.drop_constraint("ck_index_source_snapshot_hash", type_="check")
        batch.drop_constraint("ck_index_planner_prompt_hash", type_="check")
        batch.drop_column("activation_status")
        batch.drop_column("source_snapshot_hash")
        batch.drop_column("source_change_set_id")
        batch.drop_column("planner_prompt_hash")
        batch.drop_column("planner_schema_version")
        batch.drop_column("planner_model")
        batch.drop_column("planner_provider")

    with op.batch_alter_table("markdown_revisions") as batch:
        for column in (
            "after_hash",
            "before_hash",
            "change_source",
            "tool_call_id",
            "agent_turn_id",
            "agent_session_id",
            "change_set_id",
        ):
            batch.drop_index(f"ix_markdown_revisions_{column}")
        batch.drop_constraint("fk_markdown_revision_agent_turn", type_="foreignkey")
        batch.drop_constraint("fk_markdown_revision_agent_session", type_="foreignkey")
        batch.drop_constraint("fk_markdown_revision_change_set", type_="foreignkey")
        batch.drop_constraint("ck_markdown_revision_after_hash", type_="check")
        batch.drop_constraint("ck_markdown_revision_before_hash", type_="check")
        batch.drop_column("after_hash")
        batch.drop_column("before_hash")
        batch.drop_column("change_source")
        batch.drop_column("tool_call_id")
        batch.drop_column("agent_turn_id")
        batch.drop_column("agent_session_id")
        batch.drop_column("change_set_id")

    with op.batch_alter_table("markdown_notes") as batch:
        batch.drop_index("ix_markdown_notes_is_tombstoned")
        batch.drop_index("ix_markdown_notes_last_change_set_id")
        batch.drop_index("ix_markdown_notes_sync_state")
        batch.drop_index("ix_markdown_notes_content_hash")
        batch.drop_index("ix_markdown_notes_vault_file_id")
        batch.drop_constraint("fk_markdown_note_last_change_set", type_="foreignkey")
        batch.drop_constraint("fk_markdown_note_vault_file_kb_space", type_="foreignkey")
        batch.drop_constraint("ck_markdown_note_content_hash", type_="check")
        batch.drop_column("tombstoned_at")
        batch.drop_column("is_tombstoned")
        batch.drop_column("last_change_set_id")
        batch.drop_column("sync_state")
        batch.drop_column("content_hash")
        batch.drop_column("vault_relative_path")
        batch.drop_column("vault_file_id")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vault_change_entries_vault_file_id"), table_name="vault_change_entries")
    op.drop_index(op.f("ix_vault_change_entries_space_id"), table_name="vault_change_entries")
    op.drop_index(op.f("ix_vault_change_entries_operation"), table_name="vault_change_entries")
    op.drop_index(
        op.f("ix_vault_change_entries_knowledge_base_id"), table_name="vault_change_entries"
    )
    op.drop_index(op.f("ix_vault_change_entries_change_set_id"), table_name="vault_change_entries")
    op.drop_index(op.f("ix_vault_change_entries_audit_event_id"), table_name="vault_change_entries")
    op.drop_table("vault_change_entries")
    op.drop_index(op.f("ix_semantic_index_plans_vault_file_id"), table_name="semantic_index_plans")
    op.drop_index(op.f("ix_semantic_index_plans_state"), table_name="semantic_index_plans")
    op.drop_index(op.f("ix_semantic_index_plans_space_id"), table_name="semantic_index_plans")
    op.drop_index(
        op.f("ix_semantic_index_plans_knowledge_base_id"), table_name="semantic_index_plans"
    )
    op.drop_index(op.f("ix_semantic_index_plans_input_hash"), table_name="semantic_index_plans")
    op.drop_index(
        op.f("ix_semantic_index_plans_index_version_id"), table_name="semantic_index_plans"
    )
    op.drop_index(op.f("ix_semantic_index_plans_failure_code"), table_name="semantic_index_plans")
    op.drop_index(op.f("ix_semantic_index_plans_change_set_id"), table_name="semantic_index_plans")
    op.drop_table("semantic_index_plans")
    op.drop_index(op.f("ix_vault_files_sync_state"), table_name="vault_files")
    op.drop_index(op.f("ix_vault_files_space_id"), table_name="vault_files")
    op.drop_index(op.f("ix_vault_files_last_index_version_id"), table_name="vault_files")
    op.drop_index(op.f("ix_vault_files_last_change_set_id"), table_name="vault_files")
    op.drop_index(op.f("ix_vault_files_knowledge_base_id"), table_name="vault_files")
    op.drop_index(op.f("ix_vault_files_is_tombstoned"), table_name="vault_files")
    op.drop_index(op.f("ix_vault_files_file_kind"), table_name="vault_files")
    op.drop_index(op.f("ix_vault_files_file_identity"), table_name="vault_files")
    op.drop_index(op.f("ix_vault_files_content_hash"), table_name="vault_files")
    op.drop_table("vault_files")
    op.drop_index(op.f("ix_vault_change_sets_turn_id"), table_name="vault_change_sets")
    op.drop_index(op.f("ix_vault_change_sets_tool_call_id"), table_name="vault_change_sets")
    op.drop_index(op.f("ix_vault_change_sets_state"), table_name="vault_change_sets")
    op.drop_index(op.f("ix_vault_change_sets_space_id"), table_name="vault_change_sets")
    op.drop_index(op.f("ix_vault_change_sets_source"), table_name="vault_change_sets")
    op.drop_index(op.f("ix_vault_change_sets_session_id"), table_name="vault_change_sets")
    op.drop_index(op.f("ix_vault_change_sets_knowledge_base_id"), table_name="vault_change_sets")
    op.drop_index(op.f("ix_vault_change_sets_failure_code"), table_name="vault_change_sets")
    op.drop_index(op.f("ix_vault_change_sets_created_at"), table_name="vault_change_sets")
    op.drop_table("vault_change_sets")
    op.drop_index(op.f("ix_agent_usage_records_turn_id"), table_name="agent_usage_records")
    op.drop_index(op.f("ix_agent_usage_records_session_id"), table_name="agent_usage_records")
    op.drop_index(op.f("ix_agent_usage_records_recorded_at"), table_name="agent_usage_records")
    op.drop_index(op.f("ix_agent_usage_records_provider_error"), table_name="agent_usage_records")
    op.drop_table("agent_usage_records")
    op.drop_index(op.f("ix_agent_session_events_turn_id"), table_name="agent_session_events")
    op.drop_index(op.f("ix_agent_session_events_tool_call_id"), table_name="agent_session_events")
    op.drop_index(op.f("ix_agent_session_events_subagent_id"), table_name="agent_session_events")
    op.drop_index(op.f("ix_agent_session_events_session_id"), table_name="agent_session_events")
    op.drop_index(
        op.f("ix_agent_session_events_idempotency_key"), table_name="agent_session_events"
    )
    op.drop_index(op.f("ix_agent_session_events_event_type"), table_name="agent_session_events")
    op.drop_index(op.f("ix_agent_session_events_event_id"), table_name="agent_session_events")
    op.drop_index(op.f("ix_agent_session_events_created_at"), table_name="agent_session_events")
    op.drop_index(op.f("ix_agent_session_events_completed"), table_name="agent_session_events")
    op.drop_table("agent_session_events")
    op.drop_index(op.f("ix_agent_audit_events_user_id"), table_name="agent_audit_events")
    op.drop_index(op.f("ix_agent_audit_events_turn_id"), table_name="agent_audit_events")
    op.drop_index(op.f("ix_agent_audit_events_tool_name"), table_name="agent_audit_events")
    op.drop_index(op.f("ix_agent_audit_events_tool_call_id"), table_name="agent_audit_events")
    op.drop_index(op.f("ix_agent_audit_events_session_id"), table_name="agent_audit_events")
    op.drop_index(op.f("ix_agent_audit_events_event_type"), table_name="agent_audit_events")
    op.drop_index(op.f("ix_agent_audit_events_created_at"), table_name="agent_audit_events")
    op.drop_index(op.f("ix_agent_audit_events_change_set_id"), table_name="agent_audit_events")
    op.drop_table("agent_audit_events")
    op.drop_index(op.f("ix_agent_workspace_grants_user_id"), table_name="agent_workspace_grants")
    op.drop_index(op.f("ix_agent_workspace_grants_space_id"), table_name="agent_workspace_grants")
    op.drop_index(op.f("ix_agent_workspace_grants_session_id"), table_name="agent_workspace_grants")
    op.drop_index(op.f("ix_agent_workspace_grants_nonce"), table_name="agent_workspace_grants")
    op.drop_index(
        op.f("ix_agent_workspace_grants_knowledge_base_id"), table_name="agent_workspace_grants"
    )
    op.drop_index(op.f("ix_agent_workspace_grants_expires_at"), table_name="agent_workspace_grants")
    op.drop_table("agent_workspace_grants")
    op.drop_index(op.f("ix_agent_turns_state"), table_name="agent_turns")
    op.drop_index(op.f("ix_agent_turns_source_turn_id"), table_name="agent_turns")
    op.drop_index(op.f("ix_agent_turns_session_id"), table_name="agent_turns")
    op.drop_index(op.f("ix_agent_turns_native_turn_id"), table_name="agent_turns")
    op.drop_index(op.f("ix_agent_turns_native_session_id"), table_name="agent_turns")
    op.drop_table("agent_turns")
    op.drop_index(op.f("ix_vault_sync_cursors_space_id"), table_name="vault_sync_cursors")
    op.drop_index(op.f("ix_vault_sync_cursors_requires_full_scan"), table_name="vault_sync_cursors")
    op.drop_index(op.f("ix_vault_sync_cursors_knowledge_base_id"), table_name="vault_sync_cursors")
    op.drop_table("vault_sync_cursors")
    op.drop_index(op.f("ix_agent_sessions_user_id"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_state"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_space_id"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_parent_session_id"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_native_session_id"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_knowledge_base_id"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_forked_from_turn_id"), table_name="agent_sessions")
    op.drop_table("agent_sessions")
    op.drop_index(op.f("ix_agent_provider_settings_user_id"), table_name="agent_provider_settings")
    op.drop_index(op.f("ix_agent_provider_settings_provider"), table_name="agent_provider_settings")
    op.drop_index(
        op.f("ix_agent_provider_settings_health_status"), table_name="agent_provider_settings"
    )
    op.drop_table("agent_provider_settings")
    # ### end Alembic commands ###
