"""Runtime boundaries for knowledge ingestion and indexing."""

from tutor_api.knowledge.embeddings import EmbeddingAdapter, HashEmbeddingAdapter
from tutor_api.knowledge.ocr import (
    DisabledOCRAdapter,
    OCRAdapter,
    OCRDocumentResult,
    OCRError,
    OCRErrorCode,
    OCRPageCheckpoint,
    OCRPageStatus,
    PageEvidence,
    PDFiumPageRenderer,
    RenderedPage,
    TesseractOCRAdapter,
    apply_selective_ocr,
    extract_text_safely,
    normalize_ocr_languages,
)
from tutor_api.knowledge.parsers import (
    ParsedBlock,
    ParsedBlockKind,
    ParsedDocument,
    ParsedPage,
    ParseError,
    ParseErrorCode,
    VaultAttachment,
    VaultNote,
    VaultParseResult,
    WikiLink,
    parse_docx,
    parse_markdown,
    parse_obsidian_vault_zip,
    parse_pdf,
    parse_png,
)
from tutor_api.knowledge.storage import (
    MemoryObjectStorage,
    ObjectAlreadyExistsError,
    ObjectNotFoundError,
    ObjectStorage,
    StoredObject,
    build_document_object_key,
)

__all__ = [
    "DisabledOCRAdapter",
    "EmbeddingAdapter",
    "HashEmbeddingAdapter",
    "MemoryObjectStorage",
    "OCRAdapter",
    "OCRDocumentResult",
    "OCRError",
    "OCRErrorCode",
    "OCRPageCheckpoint",
    "OCRPageStatus",
    "ObjectAlreadyExistsError",
    "ObjectNotFoundError",
    "ObjectStorage",
    "PDFiumPageRenderer",
    "PageEvidence",
    "ParseError",
    "ParseErrorCode",
    "ParsedBlock",
    "ParsedBlockKind",
    "ParsedDocument",
    "ParsedPage",
    "RenderedPage",
    "StoredObject",
    "TesseractOCRAdapter",
    "VaultAttachment",
    "VaultNote",
    "VaultParseResult",
    "WikiLink",
    "apply_selective_ocr",
    "build_document_object_key",
    "extract_text_safely",
    "normalize_ocr_languages",
    "parse_docx",
    "parse_markdown",
    "parse_obsidian_vault_zip",
    "parse_pdf",
    "parse_png",
]
