"""Runtime boundaries for knowledge ingestion and indexing."""

from tutor_api.knowledge.embeddings import EmbeddingAdapter, HashEmbeddingAdapter
from tutor_api.knowledge.ocr import (
    DisabledOCRAdapter,
    OCRAdapter,
    OCRError,
    OCRErrorCode,
    extract_text_safely,
)
from tutor_api.knowledge.parsers import (
    BlockKind,
    ParsedBlock,
    ParsedDocument,
    ParsedPage,
    ParseError,
    ParseErrorCode,
    VaultAttachment,
    VaultNote,
    VaultParseResult,
    WikiLink,
    parse_docx,
    parse_markdown,
    parse_obsidian_vault_zip,
    parse_pdf,
    parse_png,
)
from tutor_api.knowledge.storage import (
    MemoryObjectStorage,
    ObjectAlreadyExistsError,
    ObjectNotFoundError,
    ObjectStorage,
    StoredObject,
    build_document_object_key,
)

__all__ = [
    "BlockKind",
    "DisabledOCRAdapter",
    "EmbeddingAdapter",
    "HashEmbeddingAdapter",
    "MemoryObjectStorage",
    "ParseError",
    "ParseErrorCode",
    "ParsedBlock",
    "ParsedDocument",
    "ParsedPage",
    "OCRAdapter",
    "OCRError",
    "OCRErrorCode",
    "ObjectAlreadyExistsError",
    "ObjectNotFoundError",
    "ObjectStorage",
    "StoredObject",
    "VaultAttachment",
    "VaultNote",
    "VaultParseResult",
    "WikiLink",
    "build_document_object_key",
    "parse_docx",
    "parse_markdown",
    "parse_obsidian_vault_zip",
    "parse_pdf",
    "parse_png",
    "extract_text_safely",
]
